name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: "google/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof master branch, as of Mar 14, 2024.
        ref: "dbe819bb94a5dc6081f440eeb4a6809c7ff66511" # wycheproof-ref

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Mar 14, 2024.
        ref: "a04fb05cf132e1405f71c12616cf0aead829909a" # x509-limbo-ref
