name: Clone test vectors
description: Clones the wycheproof and x509-limbo repositories

runs:
  using: "composite"

  steps:
    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: "google/wycheproof"
        path: "wycheproof"
        # Latest commit on the wycheproof master branch, as of Oct 28, 2023.
        ref: "d9f6ec7d8bd8c96da05368999094e4a75ba5cb3d" # wycheproof-ref

    - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      with:
        repository: "C2SP/x509-limbo"
        path: "x509-limbo"
        # Latest commit on the x509-limbo main branch, as of Feb 23, 2024.
        ref: "c8f6a4f4946076db55778ed7b3cffdab082a1a12" # x509-limbo-ref
